### ISSUE TITLE
[Question] Filtering and the NOT operator

### ISSUE THREAD

**Issue by Angelinsky7** [one2tek/larapi#71]
I've got a question about the NOT operator.
Why do we need to pass a "strange" value to use the NOT operator : 

```
{base_url}/users?filter[columnName][operator][not]=value
```

in this example i first thought that i could directly type `[not]` in the request url instead i need to use it like this : 

```
{base_url}/users?filter[name][eq][yes]=Alex
```

to look for all user without a name = Alex

can it be more like this ? (it would be more user friendly, no ?)

```
{base_url}/users?filter[name][eq][not]=Alex
```

Thanks for this package, really like it

**Comment by gentritabazi** [comment]
Thanks, **"not"** is more readable.

We need to make PR.
