### ISSUE TITLE
Selecting specific fields when using a nested include

### ISSUE THREAD

**Issue by JessengBijleng** [one2tek/larapi#74]
Is it possible to select certain field when requesting nested includes, like so:

`include=country.continent`

Say i want to select the name and the related continent from the country only, how can this be achieved? Obviousling using something like `include=country:name.continent` doesn't work. Also i feel like this markup tends to get a little akward when selecting relations and also specific fields, I would suggest something like the following:

`include=country(name).continent` 

Where everything between the parenthesis is related to selecting specific fields of a relation, and the dot notation is still used for querying the relation 

Normally when not using a nested include, selecting specific fields can be done like so:

`include=country:name`

**Comment by gentritabazi** [comment]
`include=author:id,name`

`include=author.posts:id,name`

**Comment by JessengBijleng** [comment]
Hi, 

I know that as per the docs. However, my problem is related to selecting specific fields on any relation not being the last one that is included. So in your case: How would i select specific fields from the author (for example surname and address) whilst also including the posts written by the author?

`include=author:address,surname.posts:id,name` obviously does not work. As i stated before i feel like the syntax used for including the relations limits the select possibilities. I feel It would be more convenient using the syntax i suggested: 

`include=author(address,surname).posts(id,name)`

**Comment by gentritabazi01** [comment]
include=author:address,surname;posts:id,name

**Comment by gentritabazi** [comment]
`include=author:address,surname;author.posts:id,name` separate using '`;`' .

**Comment by JessengBijleng** [comment]
That works, thanks for the quick response!
